[versions]
#Generail UI/Nav stuff versions
agp = "8.13.0"
kotlin = "2.2.21"
coreKtx = "1.17.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
lifecycleVersion = "2.9.4"
lifecycleExtensionsVersion = "1.1.1"
navigationFragmentKtx = "2.9.5"
navigationUiKtx = "2.9.5"
recyclerview = "1.4.0"

#Testing stuff versions
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
mockitoCore = "5.20.0"
core = "1.7.0"
coreTesting = "2.2.0"

#Add Room-related dependencies versions
kotlinbomVersion = "2.2.0"
roomPagingVersion = "2.8.3"
roomVersion = "2.8.3"
hiltVersion = "2.57.2"
kspVersion = "2.2.20-2.0.3"

#Add services-related dependencies versions
playServicesCronet = "18.1.1"
playServicesLocation = "21.3.0"
playservicesmapsVersion = "19.2.0"
#Add Conscrypt version (cryptographic capabilities for secure communication and TLS-based)
conscryptAndroid = "2.5.3"
#Add Networking and HTTP stuff versions
okhttp = "5.2.1"
volley = "1.2.1"
#Add Work (threads) stuff versions
workversion = "2.11.0"
#Add Google Maps Secrets versions
googleAndroidLibrariesMapsplatformSecretsGradlePlugin = "2.0.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }

# KTX (Kotlin Extensions) of Jetpack that simplify working with other APIs
# Support for ViewModel, LiveData, Manage activity state
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleVersion" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleVersion" }
androidx-lifecycle-savedstate = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "lifecycleVersion" }
# Some UI AndroidX libraries use this lightweight import for Lifecycle
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleVersion" }
# Kotlin use lifecycle-reactivestreams-ktx
androidx-lifecycle-reactivestreams-ktx = { group = "androidx.lifecycle", name = "lifecycle-reactivestreams-ktx", version.ref = "lifecycleVersion" }
# For lifecycle extensions
android-arch-lifecycle-extensions = { group = "android.arch.lifecycle", name = "extensions", version.ref = "lifecycleExtensionsVersion" }

#Room-related stuff
# Fix Duplicate class problems by using the Kotlin BOM (Bill of Materials) to align versions of all Kotlin components
org-jetbrains-kotlin-bom = { group = "org.jetbrains.kotlin", name = "kotlin-bom", version.ref = "kotlinbomVersion" }
# Room components
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomVersion" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomVersion" }
android-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomVersion" }
# Hilt support for Room
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltVersion" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hiltVersion" }
# RxJava support for GUIs with Room
room-rxjava2 = { group = "androidx.room", name = "room-rxjava2", version.ref = "roomVersion" }
room-rxjava3 = { group = "androidx.room", name = "room-rxjava3", version.ref = "roomVersion" }
# Guava support for GUIs with Room
room-guava = { group = "androidx.room", name = "room-guava", version.ref = "roomVersion" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "roomPagingVersion" }

# Support for HTTP requests with Volley and OkHttp
volley = { module = "com.android.volley:volley", version.ref = "volley" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
# Cronet (Chromium Network) library supporting high-performance network stack - build HTTP and HTTPS requests
play-services-cronet = { module = "com.google.android.gms:play-services-cronet", version.ref = "playServicesCronet" }

# Support for Worker threads stuff - WorkManager and DownloadWorker
androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "workversion" }
# Kotlin extensions (ktx) + coroutines
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workversion" }
# optional - GCM NetworkManager support
androidx-work-gcm = { module = "androidx.work:work-gcm", version.ref = "workversion" }
# optional - Multiprocess supportdata_extraction_rules.xml
androidx-work-multiprocess = { module = "androidx.work:work-multiprocess", version.ref = "workversion" }
# optional - RxJava2 support
androidx-work-rxjava2 = { module = "androidx.work:work-rxjava2", version.ref = "workversion" }
# Support cryptographic capabilities for secure communication and TLS-based apps
conscrypt-android = { module = "org.conscrypt:conscrypt-android", version.ref = "conscryptAndroid" }

# Google Play Services... Support integration of Google Maps into Android apps
com-google-android-gms-play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playservicesmapsVersion" }
# Support integration of Google Location into Android apps
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }


#Test-related stuff
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
androidx-test-core = { module = "androidx.test:core", version.ref = "core" }
# Test helpers for Room stuff
androidx-room-testing = { group = "androidx.room", name = "room-testing", version.ref = "roomVersion" }
# Android Test helpers for Workers
androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "workversion" }
#
# Android Test helpers for GUI with Espresso
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espressoCore" }
androidx-espresso-web = { module = "androidx.test.espresso:espresso-web", version.ref = "espressoCore" }
# Android Test helpers for Mock components
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
# HILT Android plugin
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltVersion" }
# KSP plugin
ksp = { id = "com.google.devtools.ksp", version.ref = "kspVersion"}
#Google Maps Secretes plugin
google-android-libraries-mapsplatform-secrets-gradle-plugin = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "googleAndroidLibrariesMapsplatformSecretsGradlePlugin" }
